// Generated by CoffeeScript 1.12.6
(function() {
  var App, LinkAttributeParser, RegExplorer, _, colors, fs, marked, path;

  fs = require('fs');

  path = require('path');

  marked = require('marked');

  colors = require('colors');

  _ = require('lodash');

  App = {
    failures: []
  };

  RegExplorer = {
    attributes: /(\[[^\[]+\]\(.*\.md\s.+?\))/i
  };

  LinkAttributeParser = {
    imagePaths: [],
    markdownPaths: [],
    currentPath: '',
    Attributes: [],
    parse: function(file, failed) {
      var markdown, output;
      App.failures = [];
      this.printWorkingIndicator();
      this.currentPath = file.fullParentDir;
      output = fs.readFileSync(file.fullPath, 'utf-8');
      markdown = output.split("\n");
      _.each(markdown, (function(_this) {
        return function(line) {
          var attributeMatches;
          attributeMatches = RegExplorer.attributes.exec(line);
          if (attributeMatches) {
            console.log(("\nInvalid markdown link '" + attributeMatches[0] + "', titles are not supported. (Referenced from '" + file.fullPath + "')").red);
            return failed = true;
          }
        };
      })(this));
      return failed;
    },
    printWorkingIndicator: function() {
      return process.stdout.write(".");
    }
  };

  module.exports = LinkAttributeParser;

}).call(this);
